---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: default
  name: dns-check
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: dns-check
            image: kube-diagnostic-utils
            args: ["/usr/local/bin/check-dns-lookup.sh"]
            env:
              - name: "TARGET_HOSTNAME"
                value: "www.google.com"
              - name: "DNS_SERVER"
                value: ""
              - name: "SLEEP_ON_FAIL"
                value: 600
